Net-ng/kansha

static/css/responsive-kansha.css

After fix 9688dea701216299ce94b4df4b0076d360dc3ce5, there is a problem with column width. When you move card with several lines, the column width increase or decrease.
Add "width: 100%" to div added

Fixe bug with column size

---

kansha/column/comp.py

Fixed issue #27

---

kansha/authentication/oauth/forms.py
kansha/user/comp.py

Correctly set the user locale after an oauth authentication.

Fixed issue #16. 

---

static/css/login.css

Removed the `.credits` entry from `@media  (max-width:1370px)` (See @rtxm comment on issue #35)

Fixed issue #35

---

alembic/versions/1bd634091036_add_display_week_numbers.py
data/locale/fr/LC_MESSAGES/messages.po
data/locale/messages.pot
kansha/board/view.py
kansha/toolbox/calendar_widget.py
kansha/user/comp.py
kansha/user/models.py
kansha/user/user_profile.py
kansha/validator.py
static/css/responsive-kansha.css
static/js/kansha.js
tests/test_validators.py

- Add user's property display_week_numbers
- Add display_week_numbers edition in user's profile
- Add a column week numbers in a board's calendar view 
- Add a column week numbers in a card's due date popup calendar

Add Display/Hide week numbers in calendars

---

.travis.yml

Follow some recommendations in [Migrating from legacy to container-based infrastructure](http://docs.travis-ci.com/user/migrating-from-legacy/) and [Caching Dependencies and Directories](http://docs.travis-ci.com/user/caching/#pip-cache) to improve Travis CI performances.

Improve Travis CI performances

---

kansha/app/app.py
kansha/app/urls.py
kansha/app/view.py
kansha/authentication/database/forms.py
kansha/authentication/login.py
kansha/authentication/oauth/forms.py
kansha/board/comp.py
kansha/user/user_profile.py
tests/helpers.py

The text below the kansha logo was wrong on the following screens :
- registration form
- email change confirmation
- password reset

Fixed issue #18

---

static/js/kansha.js

countCards doesn't work if `col` is an id

fix countCards

---

kansha/column/view.py

Show a confirmation popup when deleting a list

---

kansha/app/app.py

- application/activity_monitor 
- application/templates

add default values in application configuration

---

kansha/board/models.py
kansha/card/models.py
kansha/checklist/models.py
kansha/column/models.py
kansha/comment/models.py
kansha/gallery/models.py
kansha/label/models.py
kansha/models.py
kansha/notifications.py
kansha/pickle.py
kansha/user/models.py
kansha/user/usermanager.py
kansha/vote/models.py
setup.py

This PR also tries to fix the "vicious bug" (User was pickling its DataUser) and makes sure models won't be pickled anymore.

change install_requires versions

---

static/css/responsive-kansha.css

Fixed broken design on small screens (issue #45)
In addition, I moved all the default CSS rules **before** the media queries

Fixed issue #45

---

kansha/user/user_profile.py
static/css/responsive-kansha.css

Fixed in this PR:
- no icon on "Profile" menu entry when using french translations
- menu entries are only clickable on their label

fix user profile menu

---

kansha/app/app.py
kansha/app/urls.py
kansha/app/view.py
kansha/services/__init__.py
kansha/services/components_repository.py
kansha/services/services_repository.py

(no service implemented in this pull request)

add services injection

---

kansha/authentication/oauth/forms.py

Fix pbm when oauth don't return email (ex twitter)

---

kansha/app/view.py
kansha/board/comp.py
kansha/board/view.py
kansha/card/view.py
kansha/checklist/view.py
kansha/column/comp.py
kansha/column/view.py
kansha/comment/view.py
kansha/description/view.py
kansha/gallery/view.py
kansha/label/view.py
kansha/title/view.py
kansha/toolbox/autocomplete.py
kansha/toolbox/calendar_widget.py
kansha/toolbox/overlay.py
kansha/toolbox/popin.py
kansha/user/user_profile.py
kansha/user/view.py
kansha/vote/view.py
static/js/kansha.js

- use py2js when generating Javascript from Python
- use javascript_url instead of computing script src

improve javascript

---

conf/kansha.cfg
doc/configuration.rst
kansha/app/app.py
kansha/app/view.py

Add a new optional entry in config file favicon.
Use default favicon if not configured.

Configurable favicon

---

kansha/board/boardconfig.py
kansha/board/comp.py
kansha/board/view.py
kansha/card/comp.py
kansha/card/view.py
kansha/checklist/comp.py
kansha/checklist/view.py
kansha/column/comp.py
kansha/column/view.py
kansha/comment/comp.py
kansha/comment/view.py
kansha/gallery/comp.py
kansha/label/__init__.py
kansha/label/comp.py
kansha/security.py
kansha/title/__init__.py
kansha/title/comp.py
kansha/title/view.py
static/css/themes/board.css
static/css/themes/kansha_flat/board.css
static/css/themes/kansha_flat/home.css
static/css/themes/kansha_flat/kansha.css

This is part of the updates to #101.

Replaced Title Component by the one from V2 prototype.

---

README.rst

Gitter badger gitter badge

---

kansha/checklist/comp.py
kansha/checklist/models.py
kansha/checklist/view.py
static/checklists/js/checklists.js
static/css/themes/board.css

This PR addresses issues pointed by @nagareproject in #101 and fixes bugs.

Cleaner and working checklist component

---

kansha/app/comp.py
kansha/app/urls.py
kansha/app/view.py
kansha/authentication/login.py

Removed useless APP class and adresses issues pointed in #101.

Simplify app/comp.py

---

kansha/board/comp.py
kansha/board/view.py
kansha/security.py

Less intrusive BoardDescription component

---

kansha/card/__init__.py
kansha/card/comp.py
kansha/card/view.py
kansha/cardextension/__init__.py
kansha/cardextension/comp.py
kansha/cardextension/view.py
kansha/checklist/comp.py
kansha/comment/comp.py
kansha/comment/view.py
kansha/description/comp.py
kansha/description/view.py
kansha/due_date/comp.py
kansha/due_date/view.py
kansha/gallery/comp.py
kansha/gallery/view.py
kansha/label/comp.py
kansha/services/components_repository.py
kansha/user/user_cards.py
kansha/user/view.py
kansha/vote/comp.py
static/css/themes/kansha.css

Cardextension fixes

---

kansha/board/comp.py
kansha/board/view.py
kansha/card/comp.py
kansha/card/models.py
kansha/card/view.py
kansha/column/comp.py
kansha/column/models.py
kansha/comment/comp.py
kansha/user/view.py
static/css/themes/kansha_flat/kansha.css

Card fixes

---

kansha/board/comp.py
kansha/column/comp.py

Column: more explicit method names

---

kansha/board/view.py
kansha/card/view.py
kansha/column/view.py
kansha/title/view.py

Thanks to @bcroq for his precious advice :+1:

Fix: don't prevent model to apply on view redisplay (Title v2)

---

kansha/app/comp.py
kansha/board/comp.py
kansha/board/models.py
kansha/board/view.py
kansha/card/comp.py
kansha/card/models.py
kansha/cardextension/comp.py
kansha/checklist/comp.py
kansha/column/comp.py
kansha/comment/comp.py
kansha/description/comp.py
kansha/description/view.py
kansha/due_date/comp.py
kansha/gallery/comp.py
kansha/label/comp.py
kansha/notifications.py
kansha/services/actionlog/__init__.py
kansha/services/actionlog/comp.py
kansha/services/actionlog/messages.py
kansha/services/actionlog/models.py
kansha/services/actionlog/view.py
kansha/user/user_cards.py
kansha/user/user_profile.py
kansha/vote/comp.py
kansha/vote/view.py

We can transmit it down the component tree, adding context by the way, so that any component can log activity without refering to upper levels.
This is part of #98.

Activity log is now an object, with context

---

kansha/board/view.py
static/css/themes/board.css
static/css/themes/home.css
static/css/themes/kansha.css
static/css/themes/kansha_flat/kansha.css
static/js/dnd.js
static/js/kansha.js

Alignment of member avatars.
More compact board menu on small screens.

Remove highlight function

---

kansha/services/search/dummyengine.py
kansha/services/search/elasticengine.py
kansha/services/search/query.py
kansha/services/search/schema.py
kansha/services/search/sqliteengine.py
tests/test_search.py

Alternative to the declarative schema for runtime built schemas.

Imperative, Incremental, « stateless » searchable document schema

---

kansha/alembic/versions/2c0a3788227_rm_display_week_numbers.py
kansha/board/view.py
kansha/toolbox/calendar_widget.py
kansha/user/comp.py
kansha/user/models.py
kansha/user/user_profile.py
static/js/kansha.js

Week numbers: comply to ISO and make as defaults.

---

kansha/services/search/elasticengine.py
kansha/services/search/query.py
kansha/services/search/schema.py
kansha/services/search/sqliteengine.py
tests/test_search.py

The search service knows nothing about schema and query internals anymore.

More object oriented search service.

---

kansha/app/comp.py

It fixes the problem of a page reload immediately after user is authenticated.

Force redirect after OAuth authentication

---

kansha/app/comp.py
kansha/board/comp.py
kansha/board/models.py
kansha/card/comp.py
kansha/card/models.py
kansha/card_addons/members/comp.py
kansha/card_addons/members/models.py
kansha/card_addons/members/view.py
kansha/column/comp.py
kansha/user/comp.py
kansha/user/models.py
kansha/user/usermanager.py

In this PR we address card membership data independently from board membership data. We'll unify membership in a future step.
Closes #141.

Extension "Card member" manages its own data

---

kansha/alembic/versions/25739bc150b9_membership.py
kansha/app/comp.py
kansha/authentication/database/forms.py
kansha/batch/clear_unconfirmed_users.py
kansha/batch/import_template.py
kansha/board/boardsmanager.py
kansha/board/comp.py
kansha/board/models.py
kansha/board/view.py
kansha/card_addons/gallery/comp.py
kansha/card_addons/members/__init__.py
kansha/card_addons/members/comp.py
kansha/card_addons/members/models.py
kansha/card_addons/members/view.py
kansha/column/comp.py
kansha/helpers.py
kansha/notifications.py
kansha/services/actionlog/comp.py
kansha/services/actionlog/view.py
kansha/user/comp.py
kansha/user/models.py
kansha/user/usermanager.py
tests/test_boards.py
tests/test_security.py

Unified membership at data level between boards and cards. Next step will be to unify at the component level.

Unified Membership (data level)

---

kansha/authentication/ldap/forms.py

See #236 for context, fixes the schema default path

Fix LDAP default config schema path
